### ISSUE TITLE
Did you already release hokuyo3d package?

### ISSUE THREAD

**Issue by DaikiMaekawa** [at-wat/hokuyo3d-release#1]
@at-wat Thanks for the cool package, but I couldn't find your hokuyo package in distribution.yaml on rosdistro. So, I mean did you already release it into ROS ecosystem?

**Comment by at-wat** [comment]
Not yet. 
I have to make a pull request and send it to rosdistro.

**Comment by DaikiMaekawa** [comment]
Do you need some help for making a pull request? BTW, you can leave it to me if you want.

Thanks again.

**Comment by DaikiMaekawa** [comment]
Thank you for your quick response! :beer:
https://github.com/ros/rosdistro/pull/9709
